name: Deploy to WordPress.org
on:
    release:
        types: [published]
jobs:
    tag:
        name: New Release
        runs-on: ubuntu-latest
        steps:
            - name: Wait until midnight UTC
              run: |
                  current_hour=$(date -u +"%H")
                  current_minute=$(date -u +"%M")
                  hours_left=$((24 - current_hour))
                  minutes_left=$((60 - current_minute))
                  total_minutes=$(( (hours_left * 60) - (60 - minutes_left) ))
                  echo "Waiting for $total_minutes minutes until midnight UTC."
                  sleep $((total_minutes * 60))
            - name: Checkout code
              uses: actions/checkout@v3
            - name: WordPress Plugin Deploy
              id: deploy
              uses: 10up/action-wordpress-plugin-deploy@stable
              with:
                  generate-zip: true
              env:
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SLUG: easy-sale-badges-for-woocommerce
            - name: Upload release asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ${{ steps.deploy.outputs.zip-path }}
                  asset_name: ${{ github.event.repository.name }}.zip
                  asset_content_type: application/zip
